version: "3.7"
services:
  compiler-explorer:
    build:
      context: .
      args:
        path_prefix: compiler-explorer
    # The handling of Ctrl+C and friends is different for PID 1. You can work
    # around this by using an init system, such as `tini`. It's a minimal but
    # very good, and built into docker by default. See
    # https://github.com/krallin/tini for details.
    init: true
    ports:
      - 8080:8080
    networks:
      - default

# When a VPN is enabled, docker-compose refuses to work. This bypasses that by
# creating a separate docker network that somehow works better.
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.9.0/24
