version: "3"
services:
  compiler-explorer:
    build:
      context: .
      args:
        path_prefix: compiler-explorer
    ports:
      - 8080:8080
    networks:
      - default

# When a VPN is enabled, docker-compose refuses to work. This bypasses that by
# creating a separate docker network that somehow works better.
networks:
  default:
    ipam:
      config:
        - subnet: 192.168.9.0/24
